apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ssl-update-job
  labels:
    component: tls
    role: ssl-management
spec:
  schedule: "0 0 */5 * *" # midnight every 5 days
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            component: tls
            role: ssl-management
        spec:
          serviceAccount: ssl-management-service-account
          containers:
          - image: eaybars/nginx
            name: ssl-updater
            args: ["--update-tls"]
            ports:
            - containerPort: 80
              name: http
            resources:
              requests:
                memory: "100Mi"
                cpu: 100m
            env:
            - name: UPDATE_DEPLOYMENT # will force an update on the specified deployment, which should point to your nginx
              value: "nginx-ssl" # deployment name in deployment.yaml
            volumeMounts:
            - name: letsencrypt
              mountPath: /etc/letsencrypt
          volumes:
          - name: letsencrypt
            persistentVolumeClaim:
              claimName: letsencrypt
