apiVersion: v1
kind: PersistentVolume
metadata:
  name: letsencrypt
  labels:
    component: tls
    role: ssl-management
spec:
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: standard
  capacity:
    storage: 100Mi
  hostPath: # for demonstration purposes only,
            # awsElasticBlockStore, azureDisk, gcePersistentDisk or something alike should be preferred for production
    path: "/data/letsencrypt"